#!/usr/bin/bash

# Change wallpaper and use wall to change the theme

change_wallpaper

# Mount disks

sudo mkdir -p /run/media/justalternate/HDD
sudo mkdir -p /run/media/justalternate/SDD
sudo mount /dev/sda1 /run/media/justalternate/HDD &
sudo mount /dev/sdb1 /run/media/justalternate/SDD &

# Start the network manager applet
nm-applet &
# Start the activity-watcher
# aw-qt &
