#!/usr/bin/bash

# Change wallpaper and use wall to change the theme

file=$(ls ~/Divers/wallpaper/ | shuf -n 1)
swaybg --output '*' --image ~/Divers/wallpaper/$file &
wal -i ~/Divers/wallpaper/$file &
~/.config/waybar/launch.sh &

# Unlock brightness control
sudo chmod a+rw /sys/class/backlight/amdgpu_bl1/brightness

# Start the network manager applet
nm-applet &
# Start the activity-watcher
aw-qt &
